services:
  db:
    container_name: db
    image: postgres:17
    restart: always
    env_file:
      - ../backend/.env
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: FB1atQfXCPptY7I7BuMsAX91bGcTXx4R
      POSTGRES_DB: db
    ports:
      - "3801:5432"

  backend:
    build:
      context: ../backend
    container_name: backend
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/usr/app 
    ports:
      - "5001:5001"
    depends_on:
      - db 

  angular:
    container_name: angular
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/usr/app  
